var oneBtn = document.getElementById('calc-one')
var twoBtn = document.getElementById('calc-two')
var threeBtn = document.getElementById('calc-three')
var fourBtn = document.getElementById('calc-four')
var fiveBtn = document.getElementById('calc-five')
var sixBtn = document.getElementById('calc-six')
var sevenBtn = document.getElementById('calc-seven')
var eightBtn = document.getElementById('calc-eight')
var nineBtn = document.getElementById('calc-nine')
var zeroBtn = document.getElementById('calc-zero')

var display = document.getElementById('display')
var clearBtn = document.getElementById('calc-clear')
var pm = document.getElementById('calc-pm')

